name: RailsTest

on:
  push:
    paths-ignore:
      - README.md
      - docs/**
      - Dockerfile
      - docker-compose.yml

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.0

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install & Prepare database
        run: |
          gem install bundler
          bundle install
          bin/rails db:prepare
      - name: Run tests
        run: bin/rails test

    env:
      DB_HOST: postgres # this is needed
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: test
