name: RailsTest

on:
  push:
    paths-ignore:
      - README.md
      - docs/**
      - Dockerfile
      - docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    container:
      image: ruby:2.6.5
      env:
        RAILS_ENV: test
        # DB_HOST: postgres # this is needed

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --path vendor/bundle --jobs 4 --retry 3
          bin/rails db:prepare
          bin/rails test
